# Generated by Django 2.0.3 on 2018-04-24 16:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('mail', models.EmailField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('site', models.URLField()),
                ('statut', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AssociationsManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entry', models.DateTimeField()),
                ('ticket_number', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_begin', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('date_deadline', models.DateTimeField()),
                ('validated', models.BooleanField()),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('place', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('size_intern', models.IntegerField()),
                ('size_extern', models.IntegerField()),
                ('priority', models.CharField(choices=[('PR', 'Premium'), ('PA', 'Payant'), ('FR', 'Gratuit')], max_length=2)),
                ('token_staff', models.UUIDField()),
                ('association_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.Association')),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'ajout du membre")),
                ('association_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.Association')),
            ],
            options={
                'verbose_name': 'Liste des membres des associations',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.Event')),
            ],
        ),
        migrations.CreateModel(
            name='SystemAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=100)),
                ('mail_secondary', models.EmailField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme'), ('N', 'Non binaire')], max_length=1)),
                ('inscription_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.User'),
        ),
        migrations.AddField(
            model_name='members',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.User'),
        ),
        migrations.AddField(
            model_name='attend',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.Event'),
        ),
        migrations.AddField(
            model_name='attend',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='database.User'),
        ),
    ]
