# Generated by Django 2.0.4 on 2018-06-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20180625_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='boutique',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
