# Generated by Django 2.0.4 on 2018-06-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_event_boutique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='boutique',
            field=models.EmailField(max_length=100),
        ),
    ]
