# Generated by Django 2.0.3 on 2018-04-22 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('association', '0001_initial'),
        ('user_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entry', models.DateTimeField()),
                ('ticket_number', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_begin', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('date_deadline', models.DateTimeField()),
                ('validated', models.BooleanField()),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('place', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('size_intern', models.IntegerField()),
                ('size_extern', models.IntegerField()),
                ('priority', models.CharField(choices=[('PR', 'Premium'), ('PA', 'Payant'), ('FR', 'Gratuit')], max_length=2)),
                ('token_staff', models.UUIDField()),
                ('association_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='association.Association')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='event.Event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_settings.User')),
            ],
        ),
        migrations.AddField(
            model_name='attend',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='event.Event'),
        ),
        migrations.AddField(
            model_name='attend',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_settings.User'),
        ),
    ]
